FROM php:8.2-apache

RUN a2enmod rewrite

RUN apt-get update
RUN apt-get install -y libzip-dev git wget unzip --no-install-recommends
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update
RUN apt-get -y install cron

RUN apt-get update
RUN apt-get install -y libsodium-dev

RUN docker-php-ext-install pdo
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip
RUN docker-php-ext-install bcmath
RUN docker-php-ext-enable sodium

RUN wget https://getcomposer.org/download/2.7.7/composer.phar
RUN mv composer.phar /usr/bin/composer
RUN chmod +x /usr/bin/composer

COPY servers/http/apache/apache.conf /etc/apache2/sites-enabled/000-default.conf
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

WORKDIR /var/www

CMD ["apache2-foreground"]

ENTRYPOINT ["/entrypoint.sh"]
